// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: NetProtocol.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace logicProtocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SangoMessage : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public SendParameters sendParameters { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public SendMessages sendMessages { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendMessages : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public LoginReq loginReq { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SendParameters : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public OperationCode operationCode { get; set; } = OperationCode.Default;

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public MessageCommand messageCommand { get; set; } = MessageCommand.OperationRequest;

        [global::ProtoBuf.ProtoMember(3)]
        [global::System.ComponentModel.DefaultValue(ErrorCode.AccountDataError)]
        public ErrorCode errorCode
        {
            get { return __pbn__errorCode ?? ErrorCode.AccountDataError; }
            set { __pbn__errorCode = value; }
        }
        public bool ShouldSerializeerrorCode() => __pbn__errorCode != null;
        public void ReseterrorCode() => __pbn__errorCode = null;
        private ErrorCode? __pbn__errorCode;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginReq : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"acct", IsRequired = true)]
        public string Acct { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"pass", IsRequired = true)]
        public string Pass { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LoginRsp : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"userinfo", IsRequired = true)]
        public UserInfo Userinfo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UserInfo : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public int Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string nickName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperationCode
    {
        Default = 1,
        Login = 2,
        Register = 3,
        SyncPlayerData = 4,
        SyncPlayerTransform = 5,
        SyncPlayerAccount = 6,
        AttackCommand = 7,
        AttackDamage = 8,
        ChooseAvater = 9,
        ItemEnhance = 10,
        MissionUpdate = 11,
        Chat = 12,
        Shop = 13,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum MessageCommand
    {
        OperationRequest = 1,
        OperationResponse = 2,
        EventData = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ErrorCode
    {
        [global::ProtoBuf.ProtoEnum(Name = @"Account_Data_Error")]
        AccountDataError = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"Server_Data_Error")]
        ServerDataError = 2,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
