# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResProtocol.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ResProtocol.proto',
  package='SangoResProtocol',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11ResProtocol.proto\x12\x10SangoResProtocol\")\n\rMissionConfig\x12\n\n\x02Id\x18\x01 \x01(\x05\x12\x0c\n\x04Name\x18\x02 \x01(\tb\x06proto3'
)




_MISSIONCONFIG = _descriptor.Descriptor(
  name='MissionConfig',
  full_name='SangoResProtocol.MissionConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='Id', full_name='SangoResProtocol.MissionConfig.Id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='Name', full_name='SangoResProtocol.MissionConfig.Name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['MissionConfig'] = _MISSIONCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MissionConfig = _reflection.GeneratedProtocolMessageType('MissionConfig', (_message.Message,), {
  'DESCRIPTOR' : _MISSIONCONFIG,
  '__module__' : 'ResProtocol_pb2'
  # @@protoc_insertion_point(class_scope:SangoResProtocol.MissionConfig)
  })
_sym_db.RegisterMessage(MissionConfig)


# @@protoc_insertion_point(module_scope)
