// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: ResProtocol.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace SangoResProtocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionConfigList : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"Lst")]
        public global::System.Collections.Generic.List<MissionConfig> Lsts { get; } = new global::System.Collections.Generic.List<MissionConfig>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MissionConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(3, Name = @"Reward")]
        public global::System.Collections.Generic.List<Reward> Rewards { get; } = new global::System.Collections.Generic.List<Reward>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Reward : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public int Id { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        public int Num { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
